# Generated by Django 3.2 on 2021-04-30 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='male', max_length=25)),
                ('contact_number', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField()),
                ('electricity_meter_number', models.CharField(max_length=200)),
                ('water_meter_number', models.CharField(max_length=200)),
                ('employment_status', models.CharField(choices=[('employed', 'Employed'), ('unemployed', 'Unemployed'), ('self_employed', 'Self_employed')], default='unemployed', max_length=20)),
            ],
        ),
    ]
